### ISSUE TITLE
BetterBags

### ISSUE THREAD

**Issue by capachow** [fang2hou/AdiBagsElvUISkin#1]
Any chance we can get support for BetterBags too? The AdiBags replacement that is further developed/supported since AdiBags is now abandoned. Thank you!

https://www.curseforge.com/wow/addons/better-bags

**Comment by I-AM-T3X** [comment]
I would love this also

**Comment by fang2hou** [comment]
Yeah, I will create a Better Bags version later.

**Comment by fang2hou** [comment]
Here is the new BetterBagsElvUISkin!
https://github.com/fang2hou/BetterBagsElvUISkin
